"""PNG tEXt/iTXt/zTXt generator product-name hints (#120).

AI_META_HINTS covers vendors (OpenAI, Anthropic, ...) but not the product
names generators actually write into tEXt "Software" / "Creator" /
"parameters" keys (ChatGPT, DALL-E, Midjourney, ...). These tests pin the
key-scoped product matching: a generator field names a well-known product
→ AI metadata; the same words in free text (Comment) stay clean.
"""

from __future__ import annotations

import struct
import sys
import zlib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(SCRIPTS))

from image_meta import AI_GENERATOR_PRODUCTS, inspect_image, inspect_png, strip_png

# Product names from the issue's repro table.
ISSUE_PRODUCTS = [
    "ChatGPT",
    "DALL-E",
    "Midjourney",
    "Stable Diffusion",
    "Gemini",
    "Imagen",
    "Adobe Firefly",
    "Grok",
    "Sora",
]


def _png_chunk(ctype: bytes, payload: bytes) -> bytes:
    crc = zlib.crc32(ctype)
    crc = zlib.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


def _minimal_png_with_text_chunk(ctype: bytes, payload: bytes) -> bytes:
    sig = b"\x89PNG\r\n\x1a\n"
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0)
    idat = zlib.compress(b"\x00\x00\x00")
    return (
        sig
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(ctype, payload)
        + _png_chunk(b"IDAT", idat)
        + _png_chunk(b"IEND", b"")
    )


def _text(key: str, value: str) -> bytes:
    return key.encode("latin-1") + b"\x00" + value.encode("latin-1")


@pytest.mark.parametrize("product", ISSUE_PRODUCTS)
def test_software_tag_naming_generator_flags_ai(product: str):
    data = _minimal_png_with_text_chunk(b"tEXt", _text("Software", product))
    has_c2pa, has_ai, findings = inspect_png(data)
    assert has_c2pa is False
    assert has_ai is True
    assert any("AI generator" in f and product in f for f in findings)


@pytest.mark.parametrize("product", [p.decode("ascii") for p in AI_GENERATOR_PRODUCTS])
def test_every_generator_product_hint_matches_in_software_tag(product: str):
    data = _minimal_png_with_text_chunk(b"tEXt", _text("Software", product))
    _has_c2pa, has_ai, findings = inspect_png(data)
    assert has_ai is True
    assert any("AI generator" in f for f in findings)


def test_creator_and_parameters_keys_are_scoped():
    creator = _minimal_png_with_text_chunk(b"tEXt", _text("Creator", "DALL-E 3"))
    assert inspect_png(creator)[1] is True
    parameters = _minimal_png_with_text_chunk(
        b"tEXt", _text("parameters", "Steps: 20, Sampler: DPM++ 2M, Model: SDXL base 1.0")
    )
    assert inspect_png(parameters)[1] is True
    # Model filenames (sd_xl_base_1.0) are not product names and stay clean.
    plain_model = _minimal_png_with_text_chunk(
        b"tEXt", _text("parameters", "Steps: 20, Sampler: DPM++ 2M, Model: sd_xl_base_1.0")
    )
    assert inspect_png(plain_model)[1] is False


def test_vendor_name_still_flags_via_flat_hints():
    data = _minimal_png_with_text_chunk(b"tEXt", _text("Software", "OpenAI"))
    _has_c2pa, has_ai, findings = inspect_png(data)
    assert has_ai is True
    assert any("OpenAI" in f for f in findings)


def test_generator_word_in_comment_does_not_false_positive():
    data = _minimal_png_with_text_chunk(
        b"tEXt",
        _text("Comment", "Hiking near the Gemini constellation with my dog Sora"),
    )
    _has_c2pa, has_ai, findings = inspect_png(data)
    assert has_ai is False
    assert findings == []


def test_generated_by_comment_still_flags_via_flat_hints():
    data = _minimal_png_with_text_chunk(b"tEXt", _text("Comment", "Generated by AI"))
    _has_c2pa, has_ai, _findings = inspect_png(data)
    assert has_ai is True


def test_lowercase_key_and_value_match():
    data = _minimal_png_with_text_chunk(b"tEXt", _text("software", "chatgpt"))
    _has_c2pa, has_ai, findings = inspect_png(data)
    assert has_ai is True
    assert any("AI generator" in f for f in findings)


def test_ztext_compressed_software_matches():
    payload = b"Software\x00\x00" + zlib.compress(b"ChatGPT")
    data = _minimal_png_with_text_chunk(b"zTXt", payload)
    _has_c2pa, has_ai, findings = inspect_png(data)
    assert has_ai is True
    assert any("AI generator" in f for f in findings)


def test_itext_software_matches():
    # iTXt: keyword \0 comp-flag(0) comp-method(0) \0 lang \0 tkey \0 text
    payload = b"Software\x00\x00\x00\x00\x00ChatGPT"
    data = _minimal_png_with_text_chunk(b"iTXt", payload)
    _has_c2pa, has_ai, findings = inspect_png(data)
    assert has_ai is True
    assert any("AI generator" in f for f in findings)


@pytest.mark.parametrize(
    ("ctype", "payload"),
    [
        (b"zTXt", b"Comment\x00\x00" + zlib.compress(b"Generated by AI")),
        (
            b"iTXt",
            b"Comment\x00\x01\x00\x00\x00" + zlib.compress(b"Generated by AI"),
        ),
    ],
)
def test_compressed_text_flat_hint_matches_and_is_dropped(ctype: bytes, payload: bytes):
    data = _minimal_png_with_text_chunk(ctype, payload)
    _has_c2pa, has_ai, findings = inspect_png(data)
    assert has_ai is True
    assert any("Generated by" in f for f in findings)

    cleaned, actions = strip_png(data, strip_all_text=False)
    assert ctype not in cleaned
    assert any("drop" in action for action in actions)


def test_strip_keep_mode_drops_generator_tagged_chunk():
    data = _minimal_png_with_text_chunk(b"tEXt", _text("Software", "ChatGPT"))
    cleaned, actions = strip_png(data, strip_all_text=False)
    assert b"ChatGPT" not in cleaned
    assert any("drop" in a for a in actions)


def test_strip_keep_mode_keeps_benign_text_chunk():
    data = _minimal_png_with_text_chunk(
        b"tEXt", _text("Comment", "Hiking near the Gemini constellation")
    )
    cleaned, actions = strip_png(data, strip_all_text=False)
    assert b"Gemini" in cleaned
    assert not any("drop" in a for a in actions)


def test_inspect_image_end_to_end(tmp_path: Path):
    src = tmp_path / "chatgpt.png"
    src.write_bytes(_minimal_png_with_text_chunk(b"tEXt", _text("Software", "ChatGPT")))
    report = inspect_image(src)
    assert report.has_ai_metadata is True
    assert any("AI generator" in f for f in report.findings)
