"""Tests for native stdlib XLSX and PPTX container metadata & Layer A text scrubbing."""

from __future__ import annotations

import io
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(SCRIPTS))

from container_meta import (
    clean_container,
    clean_docx,
    clean_pptx,
    clean_xlsx,
    detect_container_format,
    inspect_container,
    inspect_docx,
    inspect_pptx,
    inspect_xlsx,
)
from format_dispatch import classify, classify_bytes

from tests.test_clean_image import _minimal_jpeg_with_app11, _minimal_png_with_text


def _create_synthetic_xlsx(
    *,
    creator: str = "ChatGPT",
    app: str = "Microsoft 365 Copilot",
    shared_text: str = "Quarterly\u200bReport",
    with_custom_xml: bool = True,
    with_c2pa_image: bool = True,
) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # [Content_Types].xml
        zf.writestr(
            "[Content_Types].xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Default Extension="png" ContentType="image/png"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
  <Override PartName="/docProps/custom.xml" ContentType="application/vnd.openxmlformats-officedocument.custom-properties+xml"/>
  <Override PartName="/customXml/item1.xml" ContentType="application/xml"/>
</Types>""",
        )
        # _rels/.rels
        zf.writestr(
            "_rels/.rels",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
  <Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties" Target="docProps/custom.xml"/>
  <Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXml" Target="customXml/item1.xml"/>
</Relationships>""",
        )
        # docProps/core.xml
        zf.writestr(
            "docProps/core.xml",
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <dc:title>Financial Data</dc:title>
  <dc:creator>{creator}</dc:creator>
  <cp:lastModifiedBy>AI Bot</cp:lastModifiedBy>
  <dc:description>Generated by AI</dc:description>
</cp:coreProperties>""",
        )
        # docProps/app.xml
        zf.writestr(
            "docProps/app.xml",
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">
  <Application>{app}</Application>
  <Company>OpenAI</Company>
</Properties>""",
        )
        # docProps/custom.xml
        zf.writestr(
            "docProps/custom.xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties">
  <property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="AIModel"><vt:lpwstr xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">GPT-4</vt:lpwstr></property>
</Properties>""",
        )
        # customXml
        if with_custom_xml:
            zf.writestr("customXml/item1.xml", "<customProps><ai>true</ai></customProps>")
        # xl/workbook.xml
        zf.writestr(
            "xl/workbook.xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheets><sheet name="Sheet1" sheetId="1" r:id="rId1" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/></sheets></workbook>""",
        )
        # xl/sharedStrings.xml
        zf.writestr(
            "xl/sharedStrings.xml",
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1">
  <si><t>{shared_text}</t></si>
</sst>""",
        )
        # xl/media/image1.png
        if with_c2pa_image:
            zf.writestr("xl/media/image1.png", _minimal_png_with_text())

    return buf.getvalue()


def _create_synthetic_pptx(
    *,
    creator: str = "Claude",
    app: str = "Anthropic AI",
    slide_text: str = "Slide\u200dTitle",
    with_c2pa_image: bool = True,
) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        # [Content_Types].xml
        zf.writestr(
            "[Content_Types].xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Default Extension="jpeg" ContentType="image/jpeg"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  <Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>""",
        )
        # _rels/.rels
        zf.writestr(
            "_rels/.rels",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>""",
        )
        # docProps/core.xml
        zf.writestr(
            "docProps/core.xml",
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <dc:title>Pitch Deck</dc:title>
  <dc:creator>{creator}</dc:creator>
</cp:coreProperties>""",
        )
        # docProps/app.xml
        zf.writestr(
            "docProps/app.xml",
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties">
  <Application>{app}</Application>
</Properties>""",
        )
        # ppt/presentation.xml
        zf.writestr(
            "ppt/presentation.xml",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"/>""",
        )
        # ppt/slides/slide1.xml
        zf.writestr(
            "ppt/slides/slide1.xml",
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
  <p:cSld><p:spTree><p:sp><p:txBody><a:p><a:r><a:t>{slide_text}</a:t></a:r></a:p></p:txBody></p:sp></p:spTree></p:cSld>
</p:sld>""",
        )
        # ppt/media/image1.jpeg
        if with_c2pa_image:
            zf.writestr("ppt/media/image1.jpeg", _minimal_jpeg_with_app11())

    return buf.getvalue()


def test_xlsx_detection_and_classification(tmp_path):
    xlsx_bytes = _create_synthetic_xlsx()
    assert detect_container_format(Path("sheet.xlsx")) == "xlsx"
    assert detect_container_format(Path("no_ext"), xlsx_bytes) == "xlsx"
    p = tmp_path / "test.xlsx"
    p.write_bytes(xlsx_bytes)
    assert classify(p) == "container"
    assert classify_bytes(xlsx_bytes) == "container"


def test_pptx_detection_and_classification(tmp_path):
    pptx_bytes = _create_synthetic_pptx()
    assert detect_container_format(Path("deck.pptx")) == "pptx"
    assert detect_container_format(Path("no_ext"), pptx_bytes) == "pptx"
    p = tmp_path / "test.pptx"
    p.write_bytes(pptx_bytes)
    assert classify(p) == "container"
    assert classify_bytes(pptx_bytes) == "container"


def test_xlsx_inspect_and_clean():
    xlsx_bytes = _create_synthetic_xlsx()

    # Inspect
    has_c2pa, has_ai, findings, _details = inspect_xlsx(xlsx_bytes)
    assert has_c2pa is True
    assert has_ai is True
    assert any("docProps/core.xml" in f for f in findings)
    assert any("customXml" in f for f in findings)
    assert any("xl/media/image1.png" in f for f in findings)

    # Clean
    cleaned_bytes, actions = clean_xlsx(xlsx_bytes, also_layer_a_text=True)
    assert any("scrub docProps/core.xml field dc:creator" in a for a in actions)
    assert any("drop part customXml/item1.xml" in a for a in actions)
    assert any("clean embedded media in xl/media/image1.png" in a for a in actions)
    assert any("layer A text:" in a for a in actions)

    # Inspect cleaned package
    has_c2pa_after, has_ai_after, findings_after, _ = inspect_xlsx(cleaned_bytes)
    assert has_c2pa_after is False
    assert has_ai_after is False
    assert not any("customXml" in f for f in findings_after)

    # Validate internal parts
    with zipfile.ZipFile(io.BytesIO(cleaned_bytes)) as zf:
        namelist = zf.namelist()
        assert "customXml/item1.xml" not in namelist
        assert "docProps/custom.xml" not in namelist

        # Validate core.xml preserves dc:title but empties creator/description
        core_xml = zf.read("docProps/core.xml").decode("utf-8")
        assert "<dc:title>Financial Data</dc:title>" in core_xml
        assert "<dc:creator></dc:creator>" in core_xml
        assert "ChatGPT" not in core_xml

        # Validate app.xml empties Application/Company
        app_xml = zf.read("docProps/app.xml").decode("utf-8")
        assert "<Application></Application>" in app_xml
        assert "<Company></Company>" in app_xml

        # Validate Layer A removed \u200b
        sst_xml = zf.read("xl/sharedStrings.xml").decode("utf-8")
        assert "\u200b" not in sst_xml
        assert "<t>QuarterlyReport</t>" in sst_xml

        # Validate rels pruned customXml
        rels_xml = zf.read("_rels/.rels").decode("utf-8")
        assert "customXml" not in rels_xml


def test_pptx_inspect_and_clean():
    pptx_bytes = _create_synthetic_pptx()

    # Inspect
    has_c2pa, has_ai, findings, _details = inspect_pptx(pptx_bytes)
    assert has_c2pa is True
    assert has_ai is True
    assert any("docProps/core.xml" in f for f in findings)
    assert any("ppt/media/image1.jpeg" in f for f in findings)

    # Clean
    cleaned_bytes, actions = clean_pptx(pptx_bytes, also_layer_a_text=True)
    assert any("scrub docProps/core.xml field dc:creator" in a for a in actions)
    assert any("clean embedded media in ppt/media/image1.jpeg" in a for a in actions)
    assert any("layer A text:" in a for a in actions)

    # Inspect cleaned package
    has_c2pa_after, has_ai_after, _findings_after, _ = inspect_pptx(cleaned_bytes)
    assert has_c2pa_after is False
    assert has_ai_after is False

    # Validate internal parts
    with zipfile.ZipFile(io.BytesIO(cleaned_bytes)) as zf:
        # Validate core.xml
        core_xml = zf.read("docProps/core.xml").decode("utf-8")
        assert "<dc:title>Pitch Deck</dc:title>" in core_xml
        assert "<dc:creator></dc:creator>" in core_xml
        assert "Claude" not in core_xml

        # Validate slide1.xml Layer A text
        slide_xml = zf.read("ppt/slides/slide1.xml").decode("utf-8")
        assert "\u200d" not in slide_xml
        assert "<a:t>SlideTitle</a:t>" in slide_xml


def test_docx_embedded_media_cleaning():
    # Verify DOCX embedded media (word/media/) is also cleaned
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(
            "word/document.xml",
            "<w:document><w:body><w:p><w:r><w:t>Doc</w:t></w:r></w:p></w:body></w:document>",
        )
        zf.writestr(
            "docProps/core.xml",
            "<cp:coreProperties xmlns:cp='http://schemas.openxmlformats.org/package/2006/metadata/core-properties' xmlns:dc='http://purl.org/dc/elements/1.1/'><dc:creator>Bot</dc:creator></cp:coreProperties>",
        )
        zf.writestr("word/media/image1.png", _minimal_png_with_text())

    docx_data = buf.getvalue()
    has_c2pa, _has_ai, findings, _ = inspect_docx(docx_data)
    assert has_c2pa is True
    assert any("word/media/image1.png" in f for f in findings)

    cleaned_data, actions = clean_docx(docx_data)
    assert any("clean embedded media in word/media/image1.png" in a for a in actions)

    has_c2pa_after, _, _, _ = inspect_docx(cleaned_data)
    assert has_c2pa_after is False


def test_clean_container_and_inspect_container_xlsx_pptx(tmp_path):
    xlsx_path = tmp_path / "budget.xlsx"
    xlsx_path.write_bytes(_create_synthetic_xlsx())

    rep = inspect_container(xlsx_path)
    assert rep.format == "xlsx"
    assert rep.has_c2pa is True
    assert rep.has_ai_metadata is True

    out_path = tmp_path / "budget_clean.xlsx"
    res = clean_container(xlsx_path, out_path)
    assert res["still_has_c2pa"] is False
    assert res["still_has_ai_metadata"] is False
    assert out_path.exists()
